### ISSUE TITLE
Add Virtualenvwrapper support

### ISSUE THREAD

**Issue by rodfersou** [jawshooah/pyenv-default-packages#1]
Add support of https://github.com/yyuu/pyenv-virtualenvwrapper for our folks that prefer this plugin over pyenv-virtualenv

**Comment by jawshooah** [comment]
So it doesn't look like this is something I can support with this plugin. pyenv-virtualenvwrapper simply initializes the virtualenvwrapper environment in the context of pyenv. After that, virtualenvs are created with the `mkvirtualenv` command, which pyenv has no control over.

virtualenvwrapper does provide a way to hook into different phases of virtualenv creation via [global hooks](https://virtualenvwrapper.readthedocs.org/en/latest/scripts.html). I might be able to add a script `etc/pyenv.d/virtualenvwrapper/default-packages.bash` that symlinks a hook into `$VIRTUALENVWRAPPER_HOOK_DIR`, but this seems unnecessary since a user could just as easily add the hook himself.

All in all, it doesn't seem worth it to me, since virtualenvwrapper provides its own hook workflow.

**Comment by rodfersou** [comment]
@jawshooah thank you for your research, I didn't know how virtualenvwrapper works and had no time to look at it
